# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Compute_env_concentrations_v4_cpp <- function(pts_ID, pts_ID_nxt, pts_basin_id, pts_upcount, pts_lake_out, pts_Hylak_id, pts_E_w, pts_E_up, pts_Q, pts_E_w_NXT, pts_k_NXT, pts_k_ws, pts_k_sw, pts_H_sed, pts_H, pts_poros, pts_rho_sd, pts_dist_nxt, pts_V_NXT, pts_f_rem_WWTP, pts_x, pts_y, pts_Pt_type, hl_Vol_total, hl_k, hl_k_ws, hl_Depth_avg, hl_H_sed, hl_poros, hl_rho_sd, hl_Hylak_id, hl_E_in, hl_k_sw, hl_basin_id, print) {
    .Call('_ePiE_Compute_env_concentrations_v4_cpp', PACKAGE = 'ePiE', pts_ID, pts_ID_nxt, pts_basin_id, pts_upcount, pts_lake_out, pts_Hylak_id, pts_E_w, pts_E_up, pts_Q, pts_E_w_NXT, pts_k_NXT, pts_k_ws, pts_k_sw, pts_H_sed, pts_H, pts_poros, pts_rho_sd, pts_dist_nxt, pts_V_NXT, pts_f_rem_WWTP, pts_x, pts_y, pts_Pt_type, hl_Vol_total, hl_k, hl_k_ws, hl_Depth_avg, hl_H_sed, hl_poros, hl_rho_sd, hl_Hylak_id, hl_E_in, hl_k_sw, hl_basin_id, print)
}

